### ISSUE TITLE
I want to personally thank you for make this implementation public!

### ISSUE THREAD

**Issue by frangeris** [nohous/tenda-beli#1]
This was the only resource available in the entire internet on how to interact with this device, I've spent like the entire day trying to configure it on homebridge to make it available over the network and control via Homekit

With your code I've figured out that is really that simple on making a local request over the network, I just create those siri shorcuts to send the json payload to a specific IP.

Really thank you a lot!!!

**Comment by nohous** [comment]
Glad to help. I've actually found few days later someone who was more thorough and found a way to emulate the remote server as well - https://goughlui.com/2020/02/22/reverse-engineer-tenda-beli-sp3-smart-wi-fi-plug-protocol/
